config/routes.rb
require "sidekiq/web" # require the web UI

Rails.application.routes.draw do
  resources :morning_worship_videos
  resources :video_transcriptions
  resources :video_technical_details
  resources :videos
  mount Sidekiq::Web => "/sidekiq" # access it at http://localhost:3000/sidekiq
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/video_technical_detail.rb
class VideoTechnicalDetail < ApplicationRecord
  belongs_to :video
end

app/controllers/video_technical_details_controller.rb
class VideoTechnicalDetailsController < ApplicationController
  before_action :set_video_technical_detail, only: %i[ show edit update destroy ]

  # GET /video_technical_details or /video_technical_details.json
  def index
    @video_technical_details = VideoTechnicalDetail.all
  end

  # GET /video_technical_details/1 or /video_technical_details/1.json
  def show
  end

  # GET /video_technical_details/new
  def new
    @video_technical_detail = VideoTechnicalDetail.new
  end

  # GET /video_technical_details/1/edit
  def edit
  end

  # POST /video_technical_details or /video_technical_details.json
  def create
    @video_technical_detail = VideoTechnicalDetail.new(video_technical_detail_params)

    respond_to do |format|
      if @video_technical_detail.save
        format.html { redirect_to @video_technical_detail, notice: "Video technical detail was successfully created." }
        format.json { render :show, status: :created, location: @video_technical_detail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @video_technical_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /video_technical_details/1 or /video_technical_details/1.json
  def update
    respond_to do |format|
      if @video_technical_detail.update(video_technical_detail_params)
        format.html { redirect_to @video_technical_detail, notice: "Video technical detail was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @video_technical_detail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @video_technical_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /video_technical_details/1 or /video_technical_details/1.json
  def destroy
    @video_technical_detail.destroy!

    respond_to do |format|
      format.html { redirect_to video_technical_details_path, notice: "Video technical detail was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video_technical_detail
      @video_technical_detail = VideoTechnicalDetail.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def video_technical_detail_params
      params.expect(video_technical_detail: [ :video_id, :duration, :bitrate, :file_size, :video_stream, :video_codec, :resolution, :width, :height, :frame_rate, :audio_stream, :audio_codec, :audio_sample_rate, :audio_channels ])
    end
end

app/helpers/video_technical_details_helper.rb
module VideoTechnicalDetailsHelper
end

app/views/video_technical_details/_form.html.erb
<%= form_with(model: video_technical_detail, class: "contents") do |form| %>
  <% if video_technical_detail.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(video_technical_detail.errors.count, "error") %> prohibited this video_technical_detail from being saved:</h2>

      <ul class="list-disc ml-6">
        <% video_technical_detail.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :video_id %>
    <%= form.text_field :video_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": video_technical_detail.errors[:video_id].none?, "border-red-400 focus:outline-red-600": video_technical_detail.errors[:video_id].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :duration %>
    <%= form.text_field :duration, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": video_technical_detail.errors[:duration].none?, "border-red-400 focus:outline-red-600": video_technical_detail.errors[:duration].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :bitrate %>
    <%= form.number_field :bitrate, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": video_technical_detail.errors[:bitrate].none?, "border-red-400 focus:outline-red-600": video_technical_detail.errors[:bitrate].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :file_size %>
    <%= form.number_field :file_size, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": video_technical_detail.errors[:file_size].none?, "border-red-400 focus:outline-red-600": video_technical_detail.errors[:file_size].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :video_stream %>
    <%= form.text_field :video_stream, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": video_technical_detail.errors[:video_stream].none?, "border-red-400 focus:outline-red-600": video_technical_detail.errors[:video_stream].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :video_codec %>
    <%= form.text_field :video_codec, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": video_technical_detail.errors[:video_codec].none?, "border-red-400 focus:outline-red-600": video_technical_detail.errors[:video_codec].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :resolution %>
    <%= form.text_field :resolution, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": video_technical_detail.errors[:resolution].none?, "border-red-400 focus:outline-red-600": video_technical_detail.errors[:resolution].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :width %>
    <%= form.number_field :width, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": video_technical_detail.errors[:width].none?, "border-red-400 focus:outline-red-600": video_technical_detail.errors[:width].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :height %>
    <%= form.number_field :height, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": video_technical_detail.errors[:height].none?, "border-red-400 focus:outline-red-600": video_technical_detail.errors[:height].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :frame_rate %>
    <%= form.text_field :frame_rate, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": video_technical_detail.errors[:frame_rate].none?, "border-red-400 focus:outline-red-600": video_technical_detail.errors[:frame_rate].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :audio_stream %>
    <%= form.text_field :audio_stream, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": video_technical_detail.errors[:audio_stream].none?, "border-red-400 focus:outline-red-600": video_technical_detail.errors[:audio_stream].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :audio_codec %>
    <%= form.text_field :audio_codec, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": video_technical_detail.errors[:audio_codec].none?, "border-red-400 focus:outline-red-600": video_technical_detail.errors[:audio_codec].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :audio_sample_rate %>
    <%= form.number_field :audio_sample_rate, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": video_technical_detail.errors[:audio_sample_rate].none?, "border-red-400 focus:outline-red-600": video_technical_detail.errors[:audio_sample_rate].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :audio_channels %>
    <%= form.number_field :audio_channels, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": video_technical_detail.errors[:audio_channels].none?, "border-red-400 focus:outline-red-600": video_technical_detail.errors[:audio_channels].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/video_technical_details/_video_technical_detail.html.erb
<div id="<%= dom_id video_technical_detail %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Video:</strong>
    <%= video_technical_detail.video_id %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Duration:</strong>
    <%= video_technical_detail.duration %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Bitrate:</strong>
    <%= video_technical_detail.bitrate %>
  </div>
  <div>
    <strong class="block font-medium mb-1">File size:</strong>
    <%= video_technical_detail.file_size %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Video stream:</strong>
    <%= video_technical_detail.video_stream %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Video codec:</strong>
    <%= video_technical_detail.video_codec %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Resolution:</strong>
    <%= video_technical_detail.resolution %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Width:</strong>
    <%= video_technical_detail.width %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Height:</strong>
    <%= video_technical_detail.height %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Frame rate:</strong>
    <%= video_technical_detail.frame_rate %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Audio stream:</strong>
    <%= video_technical_detail.audio_stream %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Audio codec:</strong>
    <%= video_technical_detail.audio_codec %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Audio sample rate:</strong>
    <%= video_technical_detail.audio_sample_rate %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Audio channels:</strong>
    <%= video_technical_detail.audio_channels %>
  </div>
</div>

app/views/video_technical_details/edit.html.erb
<% content_for :title, "Editing video technical detail" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing video technical detail</h1>

  <%= render "form", video_technical_detail: @video_technical_detail %>

  <%= link_to "Show this video technical detail", @video_technical_detail, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to video technical details", video_technical_details_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/video_technical_details/index.html.erb
<% content_for :title, "Video technical details" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Video technical details</h1>
    <%= link_to "New video technical detail", new_video_technical_detail_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="video_technical_details" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @video_technical_details.any? %>
      <% @video_technical_details.each do |video_technical_detail| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render video_technical_detail %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", video_technical_detail, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_video_technical_detail_path(video_technical_detail), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Destroy", video_technical_detail, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No video technical details found.</p>
    <% end %>
  </div>
</div>

app/views/video_technical_details/new.html.erb
<% content_for :title, "New video technical detail" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New video technical detail</h1>

  <%= render "form", video_technical_detail: @video_technical_detail %>

  <%= link_to "Back to video technical details", video_technical_details_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/video_technical_details/show.html.erb
<% content_for :title, "Showing video technical detail" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing video technical detail</h1>

  <%= render @video_technical_detail %>

  <%= link_to "Edit this video technical detail", edit_video_technical_detail_path(@video_technical_detail), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to video technical details", video_technical_details_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this video technical detail", @video_technical_detail, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>