config/routes.rb
require "sidekiq/web" # require the web UI

Rails.application.routes.draw do
  resources :morning_worship_videos
  resources :video_transcriptions
  resources :video_technical_details
  resources :videos
  mount Sidekiq::Web => "/sidekiq" # access it at http://localhost:3000/sidekiq
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/video_transcription.rb
class VideoTranscription < ApplicationRecord
  belongs_to :video
  has_one_attached :transcription_file
end

app/controllers/video_transcriptions_controller.rb
class VideoTranscriptionsController < ApplicationController
  before_action :set_video_transcription, only: %i[ show edit update destroy ]

  # GET /video_transcriptions or /video_transcriptions.json
  def index
    @video_transcriptions = VideoTranscription.all
  end

  # GET /video_transcriptions/1 or /video_transcriptions/1.json
  def show
  end

  # GET /video_transcriptions/new
  def new
    @video_transcription = VideoTranscription.new
  end

  # GET /video_transcriptions/1/edit
  def edit
  end

  # POST /video_transcriptions or /video_transcriptions.json
  def create
    @video_transcription = VideoTranscription.new(video_transcription_params)

    respond_to do |format|
      if @video_transcription.save
        format.html { redirect_to @video_transcription, notice: "Video transcription was successfully created." }
        format.json { render :show, status: :created, location: @video_transcription }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @video_transcription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /video_transcriptions/1 or /video_transcriptions/1.json
  def update
    respond_to do |format|
      if @video_transcription.update(video_transcription_params)
        format.html { redirect_to @video_transcription, notice: "Video transcription was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @video_transcription }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @video_transcription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /video_transcriptions/1 or /video_transcriptions/1.json
  def destroy
    @video_transcription.destroy!

    respond_to do |format|
      format.html { redirect_to video_transcriptions_path, notice: "Video transcription was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video_transcription
      @video_transcription = VideoTranscription.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def video_transcription_params
      params.expect(video_transcription: [ :video_id, :transcription_file, :language, :model, :output_format, :transcription_output_type, :transcription_text, :transcription_json ])
    end
end

app/helpers/video_transcriptions_helper.rb
module VideoTranscriptionsHelper
end

app/views/video_transcriptions/_form.html.erb
<%= form_with(model: video_transcription, class: "contents") do |form| %>
  <% if video_transcription.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(video_transcription.errors.count, "error") %> prohibited this video_transcription from being saved:</h2>

      <ul class="list-disc ml-6">
        <% video_transcription.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :video_id %>
    <%= form.text_field :video_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": video_transcription.errors[:video_id].none?, "border-red-400 focus:outline-red-600": video_transcription.errors[:video_id].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :transcription_file %>
    <%= form.file_field :transcription_file, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": video_transcription.errors[:transcription_file].none?, "border-red-400 focus:outline-red-600": video_transcription.errors[:transcription_file].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :language %>
    <%= form.text_field :language, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": video_transcription.errors[:language].none?, "border-red-400 focus:outline-red-600": video_transcription.errors[:language].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :model %>
    <%= form.text_field :model, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": video_transcription.errors[:model].none?, "border-red-400 focus:outline-red-600": video_transcription.errors[:model].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :output_format %>
    <%= form.text_field :output_format, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": video_transcription.errors[:output_format].none?, "border-red-400 focus:outline-red-600": video_transcription.errors[:output_format].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :transcription_output_type %>
    <%= form.text_field :transcription_output_type, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": video_transcription.errors[:transcription_output_type].none?, "border-red-400 focus:outline-red-600": video_transcription.errors[:transcription_output_type].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :transcription_text %>
    <%= form.textarea :transcription_text, rows: 4, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": video_transcription.errors[:transcription_text].none?, "border-red-400 focus:outline-red-600": video_transcription.errors[:transcription_text].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :transcription_json %>
    <%= form.text_field :transcription_json, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": video_transcription.errors[:transcription_json].none?, "border-red-400 focus:outline-red-600": video_transcription.errors[:transcription_json].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/video_transcriptions/_video_transcription.html.erb
<div id="<%= dom_id video_transcription %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Video:</strong>
    <%= video_transcription.video_id %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Transcription file:</strong>
    <%= link_to video_transcription.transcription_file.filename, video_transcription.transcription_file, class: "text-gray-700 underline hover:no-underline" if video_transcription.transcription_file.attached? %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Language:</strong>
    <%= video_transcription.language %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Model:</strong>
    <%= video_transcription.model %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Output format:</strong>
    <%= video_transcription.output_format %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Transcription output type:</strong>
    <%= video_transcription.transcription_output_type %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Transcription text:</strong>
    <%= video_transcription.transcription_text %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Transcription json:</strong>
    <%= video_transcription.transcription_json %>
  </div>
</div>

app/views/video_transcriptions/edit.html.erb
<% content_for :title, "Editing video transcription" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing video transcription</h1>

  <%= render "form", video_transcription: @video_transcription %>

  <%= link_to "Show this video transcription", @video_transcription, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to video transcriptions", video_transcriptions_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/video_transcriptions/index.html.erb
<% content_for :title, "Video transcriptions" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Video transcriptions</h1>
    <%= link_to "New video transcription", new_video_transcription_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="video_transcriptions" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @video_transcriptions.any? %>
      <% @video_transcriptions.each do |video_transcription| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render video_transcription %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", video_transcription, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_video_transcription_path(video_transcription), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Destroy", video_transcription, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No video transcriptions found.</p>
    <% end %>
  </div>
</div>

app/views/video_transcriptions/new.html.erb
<% content_for :title, "New video transcription" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New video transcription</h1>

  <%= render "form", video_transcription: @video_transcription %>

  <%= link_to "Back to video transcriptions", video_transcriptions_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/video_transcriptions/show.html.erb
<% content_for :title, "Showing video transcription" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing video transcription</h1>

  <%= render @video_transcription %>

  <%= link_to "Edit this video transcription", edit_video_transcription_path(@video_transcription), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to video transcriptions", video_transcriptions_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this video transcription", @video_transcription, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>