config/routes.rb
require "sidekiq/web" # require the web UI

Rails.application.routes.draw do
  resources :morning_worship_videos
  resources :video_transcriptions
  resources :video_technical_details
  resources :videos
  mount Sidekiq::Web => "/sidekiq" # access it at http://localhost:3000/sidekiq
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/video.rb
# Video Object Attributes
# * jw_org_url :string,
# * video_title :string,
# * video_duration :string,
# * local_video_file_path :string
class Video < ApplicationRecord
  has_one_attached :video_file

  has_one :video_technical_detail, dependent: :destroy
  has_one :morning_worship_video, dependent: :destroy
  has_many :video_transcriptions, dependent: :destroy

  validates :jw_org_url, presence: true
  validates :video_title, presence: true
  validates :local_video_file_path, presence: true

  enum :video_category, {
    morning_worship: 0,
    gilead_graduation: 1,
    annual_meeting: 2
  }

  after_save :assimilate_technical_details
  after_save :assimilate_video_category

  private

  def assimilate_technical_details
    VideoTechnicalDetailsAssimilationJob.perform_later(self)
  end

  def assimilate_video_category
    case video_category
    when "morning_worship"
      MorningWorshipVideoDataAggregationJob.perform_later(self)
    when "gilead_graduation"
      GileadGraduationVideo.find_or_create_by(video: self)
    when "annual_meeting"
      AnnualMeetingVideo.find_or_create_by(video: self)
    else
      Rails.logger.info("No specific assimilation required for Video ID #{id} with category #{video_category}")
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: %i[ show edit update destroy ]

  # GET /videos or /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1 or /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos or /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: "Video was successfully created." }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1 or /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: "Video was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1 or /videos/1.json
  def destroy
    @video.destroy!

    respond_to do |format|
      format.html { redirect_to videos_path, notice: "Video was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def video_params
      params.expect(video: [ :video_file, :jw_org_url, :video_title, :video_duration, :local_video_file_path, :video_category ])
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_with(model: video, class: "contents") do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul class="list-disc ml-6">
        <% video.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :video_file %>
    <%= form.file_field :video_file, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": video.errors[:video_file].none?, "border-red-400 focus:outline-red-600": video.errors[:video_file].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :jw_org_url %>
    <%= form.text_field :jw_org_url, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": video.errors[:jw_org_url].none?, "border-red-400 focus:outline-red-600": video.errors[:jw_org_url].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :local_video_file_path %>
    <%= form.text_field :local_video_file_path, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": video.errors[:local_video_file_path].none?, "border-red-400 focus:outline-red-600": video.errors[:local_video_file_path].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :video_title %>
    <%= form.text_field :video_title, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": video.errors[:video_title].none?, "border-red-400 focus:outline-red-600": video.errors[:video_title].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :video_duration %>
    <%= form.text_field :video_duration, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": video.errors[:video_duration].none?, "border-red-400 focus:outline-red-600": video.errors[:video_duration].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :video_category %>
    <%= form.select :video_category, Video.video_categories.keys.map { |k| [k.humanize(capitalize: false), k] }, { prompt: "Select a category" }, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": video.errors[:video_category].none?, "border-red-400 focus:outline-red-600": video.errors[:video_category].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/videos/_video.html.erb
<div id="<%= dom_id video %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Video File:</strong>
    <%= link_to video.video_file.filename, video.video_file, class: "text-gray-700 underline hover:no-underline" if video.video_file.attached? %>
  </div>
  <div>
    <strong class="block font-medium mb-1">jw.org url:</strong>
    <%= video.jw_org_url %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Local video file path:</strong>
    <%= video.local_video_file_path %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Video Title:</strong>
    <%= video.video_title %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Video Duration:</strong>
    <%= video.video_duration %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Video Category:</strong>
    <%= video.video_category.humanize(capitalize: false) %>
  </div>
</div>

app/views/videos/edit.html.erb
<% content_for :title, "Editing video" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing video</h1>

  <%= render "form", video: @video %>

  <%= link_to "Show this video", @video, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to videos", videos_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/videos/index.html.erb
<% content_for :title, "Videos" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Videos</h1>
    <%= link_to "New video", new_video_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="videos" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @videos.any? %>
      <% @videos.each do |video| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render video %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", video, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_video_path(video), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Destroy", video, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No videos found.</p>
    <% end %>
  </div>
</div>

app/views/videos/new.html.erb
<% content_for :title, "New video" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New video</h1>

  <%= render "form", video: @video %>

  <%= link_to "Back to videos", videos_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/videos/show.html.erb
<% content_for :title, "Showing video" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing video</h1>

  <%= render @video %>

  <%= link_to "Edit this video", edit_video_path(@video), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to videos", videos_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this video", @video, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>