config/routes.rb
require "sidekiq/web" # require the web UI

Rails.application.routes.draw do
  resources :morning_worship_videos
  resources :video_transcriptions
  resources :video_technical_details
  resources :videos
  mount Sidekiq::Web => "/sidekiq" # access it at http://localhost:3000/sidekiq
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/morning_worship_video.rb
class MorningWorshipVideo < ApplicationRecord
  belongs_to :video

  MW_TITLE_REGEX = /(\w*)\s(\w*):\s(.*)[(](.*)[)]/
end

app/controllers/morning_worship_videos_controller.rb
class MorningWorshipVideosController < ApplicationController
  before_action :set_morning_worship_video, only: %i[ show edit update destroy ]

  # GET /morning_worship_videos or /morning_worship_videos.json
  def index
    @morning_worship_videos = MorningWorshipVideo.all
  end

  # GET /morning_worship_videos/1 or /morning_worship_videos/1.json
  def show
  end

  # GET /morning_worship_videos/new
  def new
    @morning_worship_video = MorningWorshipVideo.new
  end

  # GET /morning_worship_videos/1/edit
  def edit
  end

  # POST /morning_worship_videos or /morning_worship_videos.json
  def create
    @morning_worship_video = MorningWorshipVideo.new(morning_worship_video_params)

    respond_to do |format|
      if @morning_worship_video.save
        format.html { redirect_to @morning_worship_video, notice: "Morning worship video was successfully created." }
        format.json { render :show, status: :created, location: @morning_worship_video }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @morning_worship_video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /morning_worship_videos/1 or /morning_worship_videos/1.json
  def update
    respond_to do |format|
      if @morning_worship_video.update(morning_worship_video_params)
        format.html { redirect_to @morning_worship_video, notice: "Morning worship video was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @morning_worship_video }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @morning_worship_video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /morning_worship_videos/1 or /morning_worship_videos/1.json
  def destroy
    @morning_worship_video.destroy!

    respond_to do |format|
      format.html { redirect_to morning_worship_videos_path, notice: "Morning worship video was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_morning_worship_video
      @morning_worship_video = MorningWorshipVideo.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def morning_worship_video_params
      params.expect(morning_worship_video: [ :video_id, :speaker_first_name, :speaker_last_name, :theme, :theme_scripture, :theme_scripture_text ])
    end
end

app/helpers/morning_worship_videos_helper.rb
module MorningWorshipVideosHelper
end

app/views/morning_worship_videos/_form.html.erb
<%= form_with(model: morning_worship_video, class: "contents") do |form| %>
  <% if morning_worship_video.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(morning_worship_video.errors.count, "error") %> prohibited this morning_worship_video from being saved:</h2>

      <ul class="list-disc ml-6">
        <% morning_worship_video.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :video_id %>
    <%= form.text_field :video_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": morning_worship_video.errors[:video_id].none?, "border-red-400 focus:outline-red-600": morning_worship_video.errors[:video_id].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :speaker_first_name %>
    <%= form.text_field :speaker_first_name, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": morning_worship_video.errors[:speaker_first_name].none?, "border-red-400 focus:outline-red-600": morning_worship_video.errors[:speaker_first_name].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :speaker_last_name %>
    <%= form.text_field :speaker_last_name, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": morning_worship_video.errors[:speaker_last_name].none?, "border-red-400 focus:outline-red-600": morning_worship_video.errors[:speaker_last_name].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :theme %>
    <%= form.text_field :theme, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": morning_worship_video.errors[:theme].none?, "border-red-400 focus:outline-red-600": morning_worship_video.errors[:theme].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :theme_scripture %>
    <%= form.text_field :theme_scripture, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": morning_worship_video.errors[:theme_scripture].none?, "border-red-400 focus:outline-red-600": morning_worship_video.errors[:theme_scripture].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :theme_scripture_text %>
    <%= form.textarea :theme_scripture_text, rows: 4, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": morning_worship_video.errors[:theme_scripture_text].none?, "border-red-400 focus:outline-red-600": morning_worship_video.errors[:theme_scripture_text].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/morning_worship_videos/_morning_worship_video.html.erb
<div id="<%= dom_id morning_worship_video %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Video:</strong>
    <%= morning_worship_video.video_id %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Speaker first name:</strong>
    <%= morning_worship_video.speaker_first_name %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Speaker last name:</strong>
    <%= morning_worship_video.speaker_last_name %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Theme:</strong>
    <%= morning_worship_video.theme %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Theme scripture:</strong>
    <%= morning_worship_video.theme_scripture %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Theme scripture text:</strong>
    <%= morning_worship_video.theme_scripture_text %>
  </div>
</div>

app/views/morning_worship_videos/edit.html.erb
<% content_for :title, "Editing morning worship video" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing morning worship video</h1>

  <%= render "form", morning_worship_video: @morning_worship_video %>

  <%= link_to "Show this morning worship video", @morning_worship_video, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to morning worship videos", morning_worship_videos_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/morning_worship_videos/index.html.erb
<% content_for :title, "Morning worship videos" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Morning worship videos</h1>
    <%= link_to "New morning worship video", new_morning_worship_video_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="morning_worship_videos" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @morning_worship_videos.any? %>
      <% @morning_worship_videos.each do |morning_worship_video| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render morning_worship_video %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", morning_worship_video, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_morning_worship_video_path(morning_worship_video), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Destroy", morning_worship_video, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No morning worship videos found.</p>
    <% end %>
  </div>
</div>

app/views/morning_worship_videos/new.html.erb
<% content_for :title, "New morning worship video" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New morning worship video</h1>

  <%= render "form", morning_worship_video: @morning_worship_video %>

  <%= link_to "Back to morning worship videos", morning_worship_videos_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/morning_worship_videos/show.html.erb
<% content_for :title, "Showing morning worship video" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing morning worship video</h1>

  <%= render @morning_worship_video %>

  <%= link_to "Edit this morning worship video", edit_morning_worship_video_path(@morning_worship_video), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to morning worship videos", morning_worship_videos_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this morning worship video", @morning_worship_video, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>